import type { Metadata } from "next";

import { Comfortaa } from 'next/font/google'
import "./globals.css";
import StoreProvider from "./StoreProvider";

const comfortaa = Comfortaa({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
      <body
        className={`${comfortaa.className} antialiased h-screen w-screen flex items-center justify-center`}
      >
        {children}
      </body>
      </StoreProvider>
    </html>
  );
}
